//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.Operations
{
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using Lite.Operations;
	using Photon.SocketServer;
	using Photon.SocketServer.Rpc;

	public class GetSectorInfoOperation : BaseLogicOperation
	{
		public GetSectorInfoOperation (IRpcProtocol protocol, OperationRequest request) : 
			base (protocol, request){}
	
	[DataMember(Code = BaseLogicOperation.Parameter.SectorInfoDict, IsOptional = false)]
	public string SectorInfoDict { get; set; }
	
	}
	
}

