//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logic.Operations
{
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using Lite.Operations;
	using Photon.SocketServer;
	using Photon.SocketServer.Rpc;
	
	/// <summary>
	/// Get sector info operation.
	/// </summary>
	public class GetSectorInfoOperation : Operation{
		
		public GetSectorInfoOperation (IRpcProtocol protocol, OperationRequest request) : 
			base (protocol, request){}
		
		[DataMember(Code = LogicParameterCode.SectorInfoDict, IsOptional = true)]
		public string SectorInfoDict { get; set; }
	}
	
	public class SpawnMasterClientProccessOperation : Operation{
		
		public SpawnMasterClientProccessOperation (IRpcProtocol protocol, OperationRequest request) : 
		base (protocol, request){}
		
		[DataMember(Code = LogicParameterCode.RoomID, IsOptional = false)]
		public string RoomID { get; set; }
	}

}

