//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic
{
	using System;
	using Photon.LoadBalancing;
	using ExitGames.Logging;

	/// <summary>
	/// TODO Handles all matchmaking.
	/// </summary>
	public class MatchHandler{
	
		private static readonly ILogger log = LogManager.GetCurrentClassLogger();
		
	    /// <summary>
	    /// Initializes a new instance of the <see cref="Logic"/> class.
	    /// </summary>
		public MatchHandler (){
			
			log.Debug("###################################################################################");
		}
	}
}

